
services:
  picking-app:
    container_name: picking-app
    build:
      context: ./picking-app
      dockerfile: dockerfile
    env_file:
      - ./picking-app/.env
    restart: unless-stopped
    depends_on:
      - odoo  # depends on odoo service
    ports:
      - "3000:3000"
    volumes:
      - ./picking-app/public:/app/public
      - ./picking-app/package.json:/app/package.json
      - ./picking-app/next.config.js:/app/next.config.js
      - ./picking-app/node_modules:/app/node_modules
    networks:
      - network

networks:
  network:
    driver: bridge